### ISSUE TITLE
Create a Laser

### ISSUE THREAD

**Issue by Anedumgottil** [Anedumgottil/VR-Mazmorra#13]
Graphical:
    - get a model, texture, make a prefab out of the laser
    Implementation:
    - Laser should take a speed, direction, position on construct
    - use this to immediately accelerate on spawn and move towards direction
    - if it touches the Player, run Player.damageTaken(damage)

**Comment by apodgo2** [comment]
The current implementation of NormalProjectile accomplishes this entire requirement pretty effectively as of commit e8c18d897752605d524bd3a61cd2f819c9773ea9:
https://github.com/Anedumgottil/VR-Mazmorra/blob/e8c18d897752605d524bd3a61cd2f819c9773ea9/Technodungeon/Assets/Scripts/NormalProjectile.cs

See the way the Pistol fires it's bullet in the aforementioned commit state to see how this could be implemented to make a laser. Since the gun already has a bullet, we can just use it for the Turrets and enemies as well, maybe with some minor tweaks to color, size, model, or damage value, so I'll be closing this ticket.
